name: Update Daftar Komik
on: push
permissions: write-all
jobs: {generate: {runs-on: ubuntu-latest, steps: [{uses: actions/checkout@v4}, {run: python3 generate_komik.py}, {run: bash save_komik.sh}]}}
